/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include <stdlib.h>
#include <stdio.h>
#include "vagon.h"

int
main (int argc, char *argv[])
{
	char *host;

	CLIENT *clnt;
	void  *result_2;

	long  posicion;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	posicion = (long) atoi(argv[2]);
	
	clnt = clnt_create (host, VAGON_PROG, VAGON_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
	
	//separar en otro programa
	result_2 = inicializar_1(&posicion, clnt);
	if (result_2 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
		exit (2);
	}

	//codigo del cliente

	clnt_destroy (clnt);
exit (0);
}
