/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VAGON_H_RPCGEN
#define _VAGON_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define VAGON_PROG 0x31111111
#define VAGON_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define RESERVAR 1
extern  char ** reservar_1(long *, CLIENT *);
extern  char ** reservar_1_svc(long *, struct svc_req *);
#define INICIALIZAR 2
extern  void * inicializar_1(long *, CLIENT *);
extern  void * inicializar_1_svc(long *, struct svc_req *);
extern int vagon_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define RESERVAR 1
extern  char ** reservar_1();
extern  char ** reservar_1_svc();
#define INICIALIZAR 2
extern  void * inicializar_1();
extern  void * inicializar_1_svc();
extern int vagon_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_VAGON_H_RPCGEN */
