/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <string.h>
#include <unistd.h>
#include <netdb.h>
#include <arpa/inet.h>
#include <sys/types.h>
#include <pthread.h> //for threading , link with lpthread
#include <stdbool.h>
#include <string.h>
#include <fcntl.h>
#include "vagon.h"

 static bool puestos[10][4];
 static bool inicializado;
 static	int filas;
 static	int columnas;
 static bool full = false;


char **
reservar_1_svc(long *argp, struct svc_req *rqstp)
{
	static char * result;
	char numeros[]="0123456789";
	int fila;
 	int columna;
 	div_t output;
 	int i,j;
 	char *aux = malloc(45 * sizeof(char));

	output = div(*argp, 10);
	fila = output.quot;
	columna = output.rem;
	//codigo del servidor
	/*
	fprintf(stderr,"\n   ");
	for (j=0;j<columnas;j++)
		fprintf(stderr,"%d ",j+1);
	fprintf(stderr,"\n");
	for(i=0; i<filas; i++){
		if(i<9){ 
	    	fprintf(stderr," %d|",i+1);
        }else{
            fprintf(stderr,"%d|",i+1);
        } 
		for(j=0;j<columnas;j++){
    		if(puestos[i][j]==true)
    			fprintf(stderr,"X ");
 			else
 				fprintf(stderr,"O ");
		}
		fprintf(stderr,"\n");
	}
	*/

	if(puestos[fila][columna]==true){
		if (full == false){
			bool full_aux = true;
			for(i=0; i<filas; i++)
				for(j=0; j<columnas; j++)
					if (puestos[i][j]==false){
						full_aux = false;
					}
			if(full_aux == true){
				full = true;
				result = "f";
			}else{
				*aux='o';
				result = aux;
				aux++;
				*aux=numeros[filas-1];
				aux++;
				*aux=numeros[columnas-1];
				aux++;
				for(i=0; i<filas; i++)
					for(j=0; j<columnas; j++){
						if (puestos[i][j]==true){
							*aux='1';
						}else{
							*aux='0';
						}
						aux++;
					}
				*aux='\0';

			}
		}
	}else{
		 puestos[fila][columna]=true;
		 result = "r";
	}
	/*
	fprintf(stderr,"\n   ");
	for (j=0;j<columnas;j++)
		fprintf(stderr,"%d ",j+1);
	fprintf(stderr,"\n");
	for(i=0; i<filas; i++){
		if(i<9){ 
	    	fprintf(stderr," %d|",i+1);
        }else{
            fprintf(stderr,"%d|",i+1);
        } 
		for(j=0;j<columnas;j++){
    		if(puestos[i][j]==true)
    			fprintf(stderr,"X ");
 			else
 				fprintf(stderr,"O ");
		}
		fprintf(stderr,"\n");
	}*/
	
	return &result;
}

void *
inicializar_1_svc(long *argp, struct svc_req *rqstp)
{
	static char * result;
	int i, j;
	div_t output;

	output = div(*argp, 10);
	filas = output.quot;
	columnas = output.rem;
	filas++;
	columnas++;

	//fprintf(stderr,"inicializando con filas: %d columnas: %d\n", filas, columnas);
	for(i=0; i<10; i++)
    	for(j=0;j<4;j++)
    		if(i<filas && j<columnas)
 				puestos[i][j]=false; 
 			else
 				puestos[i][j]=true; 

	return (void *) &result;
}
