/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "vagon.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <pthread.h> //for threading , link with lpthread

#include <errno.h>
#include <string.h>
#include <unistd.h>
#include <netdb.h>
#include <arpa/inet.h>
#include <sys/types.h>
#include <pthread.h> //for threading , link with lpthread
#include <stdbool.h>
#include <fcntl.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

void *run_server(void *);

static void
vagon_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		long reservar_1_arg;
		long inicializar_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case RESERVAR:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) reservar_1_svc;
		break;

	case INICIALIZAR:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) inicializar_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char *argv[])
{
   	int filas;
   	int columnas;
   	char create_vagon[] = "./vagon_creator localhost XX";
   	char numeros[] = "0123456789";
   	system("clear"); 
	//-------------------------Validacion de argumentos
	if (argc < 5) {
		fprintf(stderr,"\nuso: %s -f <filas> -c <col>\n", argv[0]);
		exit(1);
	}else 
		if(strcmp(argv[1], "-f") != 0){
			fprintf(stderr,"\nerror: no se reconoce el parametro %s \n", argv[1]);
			fprintf(stderr,"\nuso: %s -f <filas> -c <col>\n", argv[0]);
			exit(1);
		}else 
			if(strcmp(argv[3], "-c") != 0){
				fprintf(stderr,"\nerror: no se reconoce el parametro %s \n", argv[3]);
				fprintf(stderr,"\nuso: %s -f <filas> -c <col>\n", argv[0]);
				exit(1);
			}
			else{
				filas = atoi(argv[2]);
				columnas = atoi(argv[4]);
				if (filas > 10 || columnas > 4 || filas < 1 || columnas < 1){
					fprintf(stderr,"\nrango invalido: -f 10, -c: 4\n",filas,columnas);
					exit(1);
				}else{
					if(argc > 5){
						fprintf(stderr,"\nuso: %s -f <filas> -c <col>\n", argv[0]);
						exit(1);						
					}
				}
			}

	//-------------------------------------------------------------------------
	pthread_t thread_id;

	//------------------Se crea un hilo para el servicio-------------------------
	if( pthread_create( &thread_id , NULL ,  run_server , (void*) NULL) < 0)
        {
            perror("no se pudo crear el hilo");
            return 1;
        }

    //-------Se inicializa el vagon con el servicio de inicializacion-------------
    create_vagon[26]=numeros[filas-1];
    create_vagon[27]=numeros[columnas-1];

    system(create_vagon);

    pthread_join( thread_id , NULL);
}

void *run_server(void *args)
{
	register SVCXPRT *transp;

	pmap_unset (VAGON_PROG, VAGON_VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, VAGON_PROG, VAGON_VERS, vagon_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (VAGON_PROG, VAGON_VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, VAGON_PROG, VAGON_VERS, vagon_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (VAGON_PROG, VAGON_VERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
} 
